// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/alumni-core_api/biz/application/service"
	"github.com/xh-polaris/alumni-core_api/biz/infrastructure/config"
	"github.com/xh-polaris/alumni-core_api/biz/infrastructure/mapper/activity"
	"github.com/xh-polaris/alumni-core_api/biz/infrastructure/mapper/register"
	"github.com/xh-polaris/alumni-core_api/biz/infrastructure/mapper/user"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	mongoMapper := user.NewMongoMapper(configConfig)
	userService := service.UserService{
		UserMapper: mongoMapper,
	}
	activityMongoMapper := activity.NewMongoMapper(configConfig)
	registerMongoMapper := register.NewMongoMapper(configConfig)
	activityService := service.ActivityService{
		ActivityMapper: activityMongoMapper,
		RegisterMapper: registerMongoMapper,
	}
	providerProvider := &Provider{
		Config:          configConfig,
		UserService:     userService,
		ActivityService: activityService,
	}
	return providerProvider, nil
}
