// Code generated by hertz generator.

package core_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _activityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createactivityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getactivityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getactivitiesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registeractivityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateactivityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateeducationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateemploymentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getregistersMw() []app.HandlerFunc {
	// your code...
	return nil
}
